# Site settings
title: Portik Szabolcs | Junior Computer Engineer
description: Portfolio of Portik Szabolcs, a Junior Computer Engineer. Showcasing projects, skills, and experience in software development.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://portikszabolcs.github.io"

# User settings
username: Portik Szabolcs
user_description: I recently graduated with a Bachelor's degree in Computer Engineering from Sapientia Hungarian University of Transylvania. I have personal and university projects built with Vue.js, Laravel, Node.js, Flutter and Android, but I tried Java, Linux and ESP microcontroller development too. I'm focused on web and mobile development, but I'm open to other technologies and new challenges.
user_title: Junior Computer Engineer
email: portik.szabolcs@proton.me
github_username: portikszabolcs

exclude: ["package.json", "src", "node_modules"]
